name: storm_climo2
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - jupyterlab
  - xesmf
  - netcdf4
  - pydap
  - matplotlib
  - seaborn
  - rioxarray
  - dask
  - cfgrib
  - pygrib
  - pyarrow


